name: 'Chromatic'

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    # Only run if the CHROMATIC_PROJECT_TOKEN secret is available
    if: secrets.CHROMATIC_PROJECT_TOKEN
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code-and-above
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn chromatic --exit-once-uploaded --auto-accept-changes master
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
